import type { StorefrontProduct } from "@/db/catalog";

// Catálogo editorial centralizado. Os assets ficam em public/streetwear para que
// nome, foto e preço possam ser substituídos sem alterar os componentes da loja.
export const demoProducts: StorefrontProduct[] = [
  {
    id: "dp-boxy-camo-hoodie",
    name: "AOP Boxy Camo Zip Hoodie",
    slug: "daily-paper-aop-boxy-camo-zip-hoodie",
    category: "Hoodies",
    price: "R$ 1.089,90",
    priceCents: 108990,
    compareAtPrice: null,
    image: "/streetwear/dp-boxy-camo-hoodie.jpg",
    imageAlt: "Moletom Daily Paper boxy com zíper e camuflagem oliva",
    stock: 18,
  },
  {
    id: "dp-black-camo-tee",
    name: "Black Camo T-Shirt",
    slug: "daily-paper-black-camo-t-shirt",
    category: "T-Shirts",
    price: "R$ 439,90",
    priceCents: 43990,
    compareAtPrice: null,
    image: "/streetwear/dp-black-camo-tee.jpg",
    imageAlt: "Camiseta Daily Paper preta com camuflagem tonal",
    stock: 26,
  },
  {
    id: "dp-croc-camo-shorts",
    name: "Croc Camo Wide Shorts",
    slug: "daily-paper-croc-camo-wide-shorts",
    category: "Bottoms",
    price: "R$ 619,90",
    priceCents: 61990,
    compareAtPrice: "R$ 749,90",
    image: "/streetwear/dp-croc-camo-shorts.jpg",
    imageAlt: "Short amplo Daily Paper em camuflagem oliva",
    stock: 15,
  },
  {
    id: "dp-kalamata-cap",
    name: "Dias Stacked Cap Kalamata",
    slug: "daily-paper-dias-stacked-cap-kalamata",
    category: "Accessories",
    price: "R$ 349,90",
    priceCents: 34990,
    compareAtPrice: null,
    image: "/streetwear/dp-kalamata-cap.jpg",
    imageAlt: "Boné Daily Paper verde militar lavado",
    stock: 31,
  },
  {
    id: "dp-offwhite-knit",
    name: "Closed Shield Knit Sweater",
    slug: "daily-paper-closed-shield-knit-sweater",
    category: "Knitwear",
    price: "R$ 979,90",
    priceCents: 97990,
    compareAtPrice: null,
    image: "/streetwear/dp-offwhite-knit.jpg",
    imageAlt: "Suéter de malha vazada Daily Paper off-white",
    stock: 13,
  },
  {
    id: "dp-cargo-shorts",
    name: "AOP Camo Cargo Shorts",
    slug: "daily-paper-aop-camo-cargo-shorts",
    category: "Bottoms",
    price: "R$ 849,90",
    priceCents: 84990,
    compareAtPrice: null,
    image: "/streetwear/dp-cargo-shorts.jpg",
    imageAlt: "Short cargo Daily Paper com camuflagem sóbria",
    stock: 17,
  },
  {
    id: "dp-coach-jacket",
    name: "Mirage Ripstop Coach Jacket",
    slug: "daily-paper-mirage-ripstop-coach-jacket",
    category: "Jackets",
    price: "R$ 929,90",
    priceCents: 92990,
    compareAtPrice: null,
    image: "/streetwear/dp-coach-jacket.jpg",
    imageAlt: "Coach jacket Daily Paper cinza claro em ripstop",
    stock: 16,
  },
  {
    id: "dp-boxy-mesh-tee",
    name: "Dawn Blue Boxy Mesh T-Shirt",
    slug: "daily-paper-dawn-blue-boxy-mesh-t-shirt",
    category: "T-Shirts",
    price: "R$ 469,90",
    priceCents: 46990,
    compareAtPrice: null,
    image: "/streetwear/dp-boxy-mesh-tee.jpg",
    imageAlt: "Camiseta boxy Daily Paper azul escuro em mesh",
    stock: 22,
  },
  {
    id: "dp-denim-shirt",
    name: "Rahul Faded Denim Overshirt",
    slug: "daily-paper-rahul-faded-denim-overshirt",
    category: "Jackets",
    price: "R$ 1.149,90",
    priceCents: 114990,
    compareAtPrice: null,
    image: "/streetwear/dp-denim-shirt.jpg",
    imageAlt: "Overshirt Daily Paper em denim marrom lavado",
    stock: 11,
  },
  {
    id: "dp-denim-pants",
    name: "Rahul Faded Denim Pants",
    slug: "daily-paper-rahul-faded-denim-pants",
    category: "Bottoms",
    price: "R$ 1.039,90",
    priceCents: 103990,
    compareAtPrice: null,
    image: "/streetwear/dp-denim-pants.jpg",
    imageAlt: "Calça Daily Paper reta em denim marrom lavado",
    stock: 14,
  },
  {
    id: "dp-monogram-shorts",
    name: "Washed Monogram Woven Shorts",
    slug: "daily-paper-washed-monogram-woven-shorts",
    category: "Bottoms",
    price: "R$ 789,90",
    priceCents: 78990,
    compareAtPrice: null,
    image: "/streetwear/dp-monogram-shorts.jpg",
    imageAlt: "Short Daily Paper cinza lavado com monograma",
    stock: 21,
  },
  {
    id: "dp-grey-jersey-shorts",
    name: "Relaxed Dias Jersey Shorts",
    slug: "daily-paper-relaxed-dias-jersey-shorts",
    category: "Bottoms",
    price: "R$ 449,90",
    priceCents: 44990,
    compareAtPrice: null,
    image: "/streetwear/dp-grey-jersey-shorts.jpg",
    imageAlt: "Short de moletom Daily Paper cinza mescla relaxed",
    stock: 28,
  },
  {
    id: "stussy-zip-hoodie",
    name: "Link Sport Zip Hoodie",
    slug: "stussy-link-sport-zip-hoodie-faded-black",
    category: "Hoodies",
    price: "R$ 1.149,90",
    priceCents: 114990,
    compareAtPrice: null,
    image: "/streetwear/stussy-zip-hoodie.jpg",
    imageAlt: "Moletom Stüssy Link Sport preto lavado com zíper",
    stock: 12,
  },
  {
    id: "stussy-link-tee",
    name: "Link Sport Pigment Dyed Tee",
    slug: "stussy-link-sport-pigment-dyed-tee",
    category: "T-Shirts",
    price: "R$ 399,90",
    priceCents: 39990,
    compareAtPrice: null,
    image: "/streetwear/stussy-link-tee.jpg",
    imageAlt: "Camiseta Stüssy preta lavada com estampa Link Sport",
    stock: 24,
  },
  {
    id: "stussy-backpack",
    name: "Canvas Backpack Black",
    slug: "stussy-canvas-backpack-black",
    category: "Accessories",
    price: "R$ 679,90",
    priceCents: 67990,
    compareAtPrice: null,
    image: "/streetwear/stussy-backpack.jpg",
    imageAlt: "Mochila Stüssy preta em canvas",
    stock: 19,
  },
  {
    id: "stussy-cap",
    name: "Chenille S Snapback Cap",
    slug: "stussy-chenille-s-snapback-cap-sand",
    category: "Accessories",
    price: "R$ 429,90",
    priceCents: 42990,
    compareAtPrice: null,
    image: "/streetwear/stussy-cap.jpg",
    imageAlt: "Boné Stüssy snapback bege com logo chenille",
    stock: 23,
  },
  {
    id: "nike-airmax-pulse",
    name: "Air Max Pulse Anthracite",
    slug: "nike-air-max-pulse-anthracite",
    category: "Sneakers",
    price: "R$ 1.399,90",
    priceCents: 139990,
    compareAtPrice: null,
    image: "/streetwear/nike-airmax.jpg",
    imageAlt: "Tênis Nike Air Max Pulse cinza e preto",
    stock: 20,
  },
  {
    id: "puma-rsx-efekt",
    name: "RS-X Efekt Black",
    slug: "puma-rs-x-efekt-black",
    category: "Sneakers",
    price: "R$ 749,90",
    priceCents: 74990,
    compareAtPrice: null,
    image: "/streetwear/puma-rsx.png",
    imageAlt: "Tênis Puma RS-X Efekt preto",
    stock: 25,
  },
];
